"""
Constants and configuration values for the enrichment API.
"""

# Confidence Thresholds
LOW_CONFIDENCE_THRESHOLD = 0.7
ERROR_CONFIDENCE_DEFAULT = 0.1
FALLBACK_CONFIDENCE_DEFAULT = 0.3
NORMAL_CONFIDENCE_DEFAULT = 0.5

# API Limits
DEFAULT_PAGE_LIMIT = 20
MAX_PAGE_LIMIT = 100
DEFAULT_BATCH_SIZE = 10
MAX_CONCURRENT_REQUESTS = 5

# Time Windows
RECENT_ENRICHMENT_HOURS = 24

# Defaults
DEFAULT_TAGS = ["structured"]

# HTTP Status Codes
HTTP_500_INTERNAL_ERROR = 500
HTTP_404_NOT_FOUND = 404
HTTP_400_BAD_REQUEST = 400
