from typing import Any, Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field


class EnrichmentMetadata(BaseModel):
    """Metadata generated by AI enrichment"""
    description: str = Field(..., description="Concise 1-2 sentence summary")
    tags: List[str] = Field(..., description="Relevant tags from taxonomy")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score")
    entities: Optional[Dict[str, Any]] = Field(None, description="Extracted entities (names, dates, amounts)")
    estimated_size: Optional[str] = Field(None, description="Estimated dataset size (e.g., '24.5 GB' or '150 MB')")


class RecordInput(BaseModel):
    """Input record for enrichment"""
    source_system: str = Field(..., description="Source system identifier")
    entity_type: str = Field(..., description="Type of entity/data")
    raw_data: Dict[str, Any] = Field(..., description="Raw data payload")


class EnrichmentOptions(BaseModel):
    """Options for enrichment processing"""
    model: Optional[str] = Field(None, description="LLM model to use")
    include_entities: bool = Field(False, description="Extract entities")


class EnrichRequest(BaseModel):
    """Request body for /api/enrich endpoint"""
    records: List[RecordInput] = Field(..., min_length=1, description="Records to enrich")
    options: Optional[EnrichmentOptions] = Field(default_factory=EnrichmentOptions)


class EnrichedRecord(BaseModel):
    """Enriched record response"""
    id: int
    source_system: str
    entity_type: str
    raw_data: Dict[str, Any]
    enriched_metadata: EnrichmentMetadata
    ingestion_timestamp: datetime
    enrichment_timestamp: datetime
    enrichment_version: str
    
    class Config:
        from_attributes = True


class EnrichResponse(BaseModel):
    """Response from /api/enrich endpoint"""
    status: str
    enriched_count: int
    results: List[EnrichedRecord]


class QueryParams(BaseModel):
    """Query parameters for filtering enriched records"""
    tags: Optional[str] = None
    entity_type: Optional[str] = None
    source_system: Optional[str] = None
    min_confidence: Optional[float] = Field(None, ge=0.0, le=1.0, description="Minimum confidence score")
    limit: int = Field(20, ge=1, le=100)
    offset: int = Field(0, ge=0)
    search: Optional[str] = None


class EnrichedRecordsResponse(BaseModel):
    """Response for querying enriched records"""
    total: int
    page: int
    limit: int
    records: List[EnrichedRecord]


class Collection(BaseModel):
    """Collection metadata"""
    name: str
    count: int
    description: str


class CollectionsResponse(BaseModel):
    """Response for listing collections"""
    collections: List[Collection]


class EnrichmentStats(BaseModel):
    """Statistics about enrichment operations"""
    total_records: int
    total_enriched: int
    avg_confidence: float
    enrichments_by_source: Dict[str, int]
    enrichments_by_entity: Dict[str, int]
    enrichments_by_tag: Dict[str, int]
    recent_enrichments: int
    low_confidence_count: int


class AnalyticsResponse(BaseModel):
    """Response for analytics endpoint"""
    stats: EnrichmentStats
    timestamp: datetime


class DatasetRegisterRequest(BaseModel):
    """Request for registering a new dataset"""
    description: str = Field(..., description="Description of the dataset to register")


class DatasetRegisterResponse(BaseModel):
    """Response from dataset registration"""
    dataset_name: str
    description: str
    sensitivity: str
    records: int
    size: str
    compliance: List[str]
    status: str
    last_accessed: str
